title: Finite element seminar
author: Ed Bueler
email: elbueler@alaska.edu
github_username: bueler
markdown: kramdown
kramdown:
  math_engine: mathjax
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one